### ISSUE TITLE
Update and Expand Glossary

### ISSUE THREAD

**Issue by kennethpjdyer** [codership/documentation#124]
There are a number of technical concepts suggests or described in the docs that do not have clear reference entries in the glossary.  While it's not necessarily to create links to all of these entries, the glossary should supply more than what it does not.

**Comment by kennethpjdyer** [comment]
Percona Glossary: https://www.percona.com/doc/percona-xtradb-cluster/5.5/glossary.html

**Comment by kirjaamo** [comment]
@byte Can you select the desired glossary entries from the Percona glossary, and I will add them.

**Comment by byte** [comment]
@kirjaamo this is our glossary: https://galeracluster.com/library/documentation/glossary.html

This is the current Percona glossary: https://www.percona.com/doc/percona-xtradb-cluster/8.0/glossary.html

I'm not entirely sure there is stuff we should be adopting, because if you blindling pick ACID, you'll see that there is no mention of ACID in the docs. Likewise we don't talk about things like NUMA, or an InnoDB LSN. 

Now, do we need to glossary InnoDB or MyISAM storage engines? I don't think so.

Maybe the only thing that one could consider "relevant" is under the Percona XtraDB Cluster heading, cluster replication, donor node, joiner node, node, primary cluster, quorum, split brain.

**Comment by kirjaamo** [comment]
After the glossary item additions, we need links to the new items, right?

**Comment by kirjaamo** [comment]
Fixed in line with the comments above.
