### ISSUE TITLE
4.x: Document Inconsistency Voting

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#144]

**Comment by kirjaamo** [comment]
@byte Is this something I could do? If yes, where can I look for more information?

**Comment by byte** [comment]
@kirjaamo yes you could take it

Cluster Error Voting (started life as MDEV-17048 -- https://jira.mariadb.org/browse/MDEV-17048) is a new feature implemented by Alexey, and it is a protocol for nodes to decide how the cluster will react to problems in replication. When one or several nodes have an issue to apply an incoming transactions (e.g. suspected inconsistency), this new feature helps. In a 5-node cluster, if 2-nodes failed to apply the transaction, they get removed and a DBA can go in to fix what went wrong so that the nodes can rejoin the cluster.

Funny story, even MariaDB Server has an open jira for this -- documenting it -- https://jira.mariadb.org/browse/MDEV-22156

**Comment by byte** [comment]
This needs to move on; @kirjaamo this should be it's own page

https://galeracluster.com/2020/09/galera-clustering-in-mariadb-10-5-and-beyond/

**Comment by kirjaamo** [comment]
@byte, https://jira.mariadb.org/browse/MDEV-17048 mentions parameter _gcs.vote_policy_, which is not documented either. Should it be added and if yes, where can I get a description of it?

Is it ok if I write a draft of voting here, and you comment it, before I create a branch?

**Comment by kirjaamo** [comment]
For example:

**Cluster Error Voting**

Cluster error voting is a protocol for nodes to decide how the cluster reacts to problems in replication. Error voting helps, when one or several nodes have an issue to apply an incoming transactions. This can happen, for example, in the
case of suspected inconsistency.

If, for example, in a five-node cluster, two nodes fail to apply a transaction, they get removed and a the DBA can fix the issue, and the nodes can rejoin the cluster.

Inconsistency voting works, as follows:

- For transactions:
  - If applying a slave writeset fails (apply callback), an error description is passed back to the provider, and it initiates voting in the group. All nodes report the result they get for a given action, and if there is a simple majority about a given result, this result wins and the nodes that have a different result gracefully quit the group. If there is no majority, success wins. If there is no node with a successful result, another node wins.

- For TOI operations (DDLs):
  - The operation is the same as for transactions, except that also the master can initiate a vote, if DDL fails.

- Control:
  - wsrep_ignore_apply_errors bitmask controls whether the error is reported back to the provider. For example,  wsrep_ignore_apply_errors=4 ignores all DDL errors. Otherwise, any DDL error will result in a voting round. In this case, a more useful value would be 1, where only reconciling DDL errors are ignored.
  - gcs.vote_policy defines who wins in a voting round: The default value 0 means simple majority as described above. Any value >= 1 means that if success votes count is >= that value, success wins even if in minority. For example, if gcs.vote_policy=1, only the node that successfully committed a transaction would remain primary.

**Comment by byte** [comment]
> @byte, https://jira.mariadb.org/browse/MDEV-17048 mentions parameter _gcs.vote_policy_, which is not documented either. Should it be added and if yes, where can I get a description of it?
> 
> Is it ok if I write a draft of voting here, and you comment it, before I create a branch?

I couldn’t find it in the commit… so i asked the person that wrote the commit — and yes, it is undocumented everywhere…

Alexey says:
In any case, here's what it is:
When some node fails to apply a writeset, it initiates voting on the outcome. Every node then casts a vote (a hash of the error message or 0 if there was no error). If a node votes "wrong", the node is considered to be inconsistent and shuts down.
gcs.vote_policy decides on how votes are being counted and winner is chosen:
1. gcs.vote_policy == 0 means that the outcome that has more votes is chosen the winner. In case of a tie between 0 (success) and non-0 (error) outcomes, the 0 is preferred.
2. gcs.vote_policy > 0 means that if success got that many votes, it is considered a winner. In particular, if gcs.vote_policy == 1 then the behaviour is like in the good old days when an inconsistent master could crash all the slaves. Backward compatibility.

**Comment by kirjaamo** [comment]
What did you think about the voting description itself?

**Comment by kirjaamo** [comment]
Is gcs.vote_policy a dynamic parameter?

**Comment by byte** [comment]
> Is gcs.vote_policy a dynamic parameter?

no, it is not dynamic; and it has to be the same on all nodes

**Comment by byte** [comment]
> What did you think about the voting description itself?

it is sufficient but needs to include the info from alexey too

**Comment by kirjaamo** [comment]
Ready for your review in a pull request

**Comment by kirjaamo** [comment]
There are two branches for this, one for the description and one for the parameter
