### ISSUE TITLE
Improve recovery documentation

### ISSUE THREAD

**Issue by byte** [codership/documentation#282]
this might be the best resource i've seen on all the recovery methods around Galera Cluster -- it might make for a good tutorial

https://docs.openstack.org/openstack-ansible/newton/developer-docs/ops-galera-recovery.html

**Comment by kirjaamo** [comment]
@byte If I add this document to Galera Tutorials, can you make the necessary changes to the text? For example, Ansible is used in the examples. Perhaps not every implementation uses it.

The text talks about MariaDB. Can we just talk about DBMSs instead of specifying, which particular system we refer to?
