### ISSUE TITLE
wsrep_mode: value APPLIER_IGNORE_MISSING_TABLE undocumented

### ISSUE THREAD

**Issue by sciascid** [codership/documentation#423]
The default value of `wsrep_mode` is `APPLIER_IGNORE_MISSING_TABLE`.
This not documented in https://galeracluster.com/library/documentation/mysql-wsrep-options.html

**Comment by kirjaamo** [comment]
@byte Is it enough to add this value as default, or does the value need a description?

**Comment by byte** [comment]
This is interesting, because look at the differences in MariaDB Server and Percona XtraDB Cluster (PXC) also

https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_mode
https://docs.percona.com/percona-xtradb-cluster/8.0/wsrep-system-index.html#wsrep_max_ws_size

We also don't document what is APPLIER_IGNORE_MISSING_TABLE

@kirjaamo you also need to ensure that the above is documented as VALUE with an appropriate BEHAVIOUR

**Comment by kirjaamo** [comment]
@byte What is the appropriate behaviour? I cannot find anything from the Internet.

**Comment by sjaakola** [comment]
APPLIER_IGNORE_MISSING_TABLE was added as fix for issue: https://github.com/codership/mysql-wsrep-bugs/issues/1362
 The description there is:
 "Multi table update statement on two tables, where the other table is used only for join, i.e. no writes to this table, and the join table has triggers which cause DML to a third table, then the binlog events for this update will contain table map event of the triggered table."

Fix is present in commit: aca1f9acfe43f398b050a3f2d5e0ff967ebf5c27 with comment:

Implemented a "naive fix" for the issue.
In this design, the excessive tablemap event remains in binlog, but applier and replayer are relaxed to ignore failure in opening a table.
This means they ignore all open table errors, regardlesss if the failure in open was related to excessive triggered table opening or not.
The assumption is that, if the table open error is a real problem, then applying will fail later on with some other error.
    
Fix to make sure that ignored table does not remain in table cache
addition to mtr test to verify that table cache does not contains remnants of the zombie table
    
Fix to raise error and crash the node, if applying fails to open all tables
    
fixed test galera_trigger_binlog to be deterministic
added two new test cases
    
Changed the fix to be conditional and configured by wsrep_mode.
Added new wsrep_mode: APPLIER_IGNORE_MISSING_TABLE, which enables the fix to skip failures with table open at applying time, but only if
the log event contains also other tables, which are successfully opened.
APPLIER_IGNORE_MISSING_TABLE option is set as default mode in this commit.
    
The fix is now extended to raise error, if there is a real inconsistency in the database, so that a table is really missing, and a multi table operation (like UPDATE) using also the missing table.

**Comment by sjaakola** [comment]
for end user documentation, maybe following language is enough:

MySQL has anomaly to sometimes add excessive tablemap event in binlog. This can happen in use cases related to multi-table update and trigger definition to third table, which is not effectively needed in applying of the replication events. With wsrep_mode APPLIER_IGNORE_MISSING_TABLE, replication applier will ignore the failure to open such table, which would not be used in the actual applying.

**Comment by kirjaamo** [comment]
@sjaakola Description added and branch pushed, but the table with variable descriptions does not show at all. The table definition is correct to my eye. Do you have time to check?
