### ISSUE TITLE
Deprecate CHANGE MASTER TO

### ISSUE THREAD

**Issue by kirjaamo** [codership/documentation#456]
In MySQL 8.4 we use CHANGE REPLICATION SOURCE TO instead of CHANGE MASTER TO. Change this in our documentation, too. Keep the old syntax, too.

**Comment by byte** [comment]
@kirjaamo i don't know if you'll notice the review but... this issue is done, however, bigger issue (you can make another) is to ensure we change the terms overall
from the PR:
this is syntactically correct, but we probably have to change the terms master / slave to leader/follower / primary/secondary / etc

please come up with a sensible proposal - that we then all agree upon - so that the bigger change actually is to stop using master/slave like upstream has changed overall

**Comment by kirjaamo** [comment]
@byte Can we close this issue? Master/slave discussion has its own issue.
