### ISSUE TITLE
galera protocol upgrade documentation

### ISSUE THREAD

**Issue by sjaakola** [codership/documentation#475]
When galera replication protocol changes, it generally is not possible to rollback a cluster upgrade. It is not possible to install previous release in some node and join it back to cluster operating with higher protocol version.
For this, the release notes should clearly state if replication protocol has been upgraded and what consequences this has.

Also, a special best practices document should be written to describe what replication protocol upgrade means and how to deal with such upgrades.

MariaDB has a separate jira issue related to protocol upgrade problems faced in mariadb deployments:
https://jira.mariadb.org/browse/MDEV-34643

**Comment by byte** [comment]
Protocol changes documented in release notes:
release-notes-galera-25.3.22.txt:* Fix for EVS protocol stall due to exhausted send window setting. This
release-notes-galera-25.3.27.txt:* Prevent protocol downgrade on rolling upgrade (codership/galera#537)
release-notes-galera-25.3.29.txt:  when packets were lost or delayed. The communication protocol was optimized
release-notes-galera-26.4.17.txt:protocol before at least one of the existing nodes has seen at least one join
release-notes-galera-26.4.18.txt:- Fixed commit cut tracking on node leave, and bumped GCS protocol version for
release-notes-galera-26.4.19.txt:- GCS level protocol bumped, as error voting for joiner in the JOINED state was
release-notes-mysql-wsrep-8.0.22-26.5.txt:- PS protocol compatibility with MySQL-wsrep was improved.
release-notes-mysql-wsrep-8.0.36-26.17.txt:possibility of a cluster split, so the server side wsrep protocol version is

But no protocol version mentioned in release notes

**Comment by kirjaamo** [comment]
@byte Can you check the versions? I can then add a column to the table for protocol versions.

**Comment by byte** [comment]
> @byte Can you check the versions? I can then add a column to the table for protocol versions.

should tally with https://galeracluster.com/documentation/library/documentation/galera-status-variables.html#wsrep-protocol-version

**Comment by kirjaamo** [comment]
@byte We don't have matching release notes for protocol versions 5, 6, 7 and 10.
